sudo: false
 
language: node_js
 
before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
 
branches:
  only:
    - eslint
 
before_script:
  - meteor npm install
 
script:
  - npm run build:linux
  - rsync -r ../OGV-meteor.tar.gz $REMOTE_USER:$REMOTE_PASSWORD@$REMOTE_SERVER:$REMOTE_PATH