dashboard:
  image: sniok/ogv
  ports:
   - "80:80"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/yourapp
   - ROOT_URL=http://localhost
   - PORT=3000
mongo:
  image: mongo:latest